name: package_name
description: A new Dart package.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.7
  fpdart: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  mocktail: ^1.0.4
